// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzzCtH1Z59c3JgsNhzE-rRX3odz6w2QUU',
    appId: '1:24983986998:web:49269ddba3d58828210997',
    messagingSenderId: '24983986998',
    projectId: 'flutter-application-1-c3edb',
    authDomain: 'flutter-application-1-c3edb.firebaseapp.com',
    storageBucket: 'flutter-application-1-c3edb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXXvy3lXkZoj2nmfRTS1QLXR-L60tFiPI',
    appId: '1:24983986998:android:7cf99984f311ba6d210997',
    messagingSenderId: '24983986998',
    projectId: 'flutter-application-1-c3edb',
    storageBucket: 'flutter-application-1-c3edb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx2zgCuLgu1m3vZa30IZ-6COLOzeOpDWE',
    appId: '1:24983986998:ios:e165c17c4c930c3d210997',
    messagingSenderId: '24983986998',
    projectId: 'flutter-application-1-c3edb',
    storageBucket: 'flutter-application-1-c3edb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
